version: '3.8'

volumes:
  postgres_data:
  static_volume:
  nginx_conf:


services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: jemandem/yamdb_final
    restart: always
    command: gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/code/static/
      - nginx_conf:/code/conf.d/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx: 
    image: nginx:1.19-alpine
    ports:
      - "8080:80"
    volumes:
      - static_volume:/static/
      - nginx_conf:/etc/nginx/conf.d/ 
    depends_on:
      - web
